compression-level = 9
enable-magisk-update = true
parallel-job = 1

[YouTube]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced"
build-mode = "both"
version = "auto"
excluded-patches = "'Custom branding' 'Premium heading'"
included-patches = ""
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTube-Music]
enabled = true
app-name = "YouTube Music"
rv-brand = "ReVanced"
build-mode = "both"
version = "auto"
arch = "both"
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
