parallel-jobs = 1
compression-level = 9
logging-to-file = true
enable-magisk-update = true
build-mindetach-module = false

[YouTube]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced"
build-mode = "both"
version = "18.32.39"
excluded-patches = "'Custom branding' 'Premium heading'"
included-patches = ""
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
