compression-level = 9
enable-magisk-update = true

[YouTube]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced"
build-mode = "both"
version = "auto"
excluded-patches = "'Custom branding' 'Premium heading'"
included-patches = ""
exclusive-patches = false
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Music]
enabled = true
app-name = "YouTube Music"
rv-brand = "ReVanced"
build-mode = "both"
version = "auto"
arch = "both"
excluded-patches = ""
included-patches = ""
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
