compression-level = 9
logging-to-file = true
enable-magisk-update = true
build-mindetach-module = false

[YouTube]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced"
build-mode = "both"
version = "auto"
excluded-patches = "'Custom branding' 'Premium heading'"
included-patches = ""
exclusive-patches = false
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
