parallel-jobs = 1
compression-level = 9
logging-to-file = true
enable-magisk-update = true
build-mindetach-module = false

[YouTube]
enabled = false
app-name = "YouTube"
rv-brand = "ReVanced"
build-mode = "both"
version = "auto"
excluded-patches = "custom-branding premium-heading"
included-patches = ""
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[TikTok]
enabled = true
app-name = "TikTok"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
exclusive-patches = false
