compression-level = 9
logging-to-file = true
enable-magisk-update = true
build-mindetach-module = false

[YouTube]
enabled = false
app-name = "YouTube"
rv-brand = "ReVanced"
build-mode = "both"
version = "auto"
excluded-patches = "custom-branding premium-heading"
included-patches = ""
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[YouTube-Extended]
enabled = false
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "auto"
excluded-patches = "custom-branding-icon-revancify-blue custom-branding-youtube-name"
included-patches = "materialyou"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"
